# Generated by Django 3.2.6 on 2021-08-29 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0002_auto_20210329_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogsmodel',
            options={'ordering': ('-updated',), 'verbose_name': 'Dialog', 'verbose_name_plural': 'Dialogs'},
        ),
        migrations.AddField(
            model_name='dialogsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddIndex(
            model_name='dialogsmodel',
            index=models.Index(fields=['-updated'], name='private_chat_dialog_update_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['pid'], name='private_chat_message_pid_idx'),
        ),
    ]
