# Generated by Django 3.2.6 on 2021-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0003_auto_20210829_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='preview_description',
            field=models.TextField(blank=True, verbose_name='preview description'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='preview_thumbnail',
            field=models.URLField(blank=True, verbose_name='preview thumbnail'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='preview_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='preview title'),
        ),
    ]
